name: permission_handler
description: Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
version: 10.1.0
repository: https://github.com/anocean2/flutter-permission-handler
issue_tracker: https://github.com/anocean2/flutter-permission-handler/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: permission_handler_android
      ios:
        default_package: permission_handler_apple
      windows:
        default_package: permission_handler_windows

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  permission_handler_android:
    path: ../../flutter-permission-handler/permission_handler_android
  permission_handler_apple:
    path: ../../flutter-permission-handler/permission_handler_apple
  permission_handler_windows:
    path: ../../flutter-permission-handler/permission_handler_windows
  permission_handler_platform_interface:
    path: ../../flutter-permission-handler/permission_handler_platform_interface

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  plugin_platform_interface: ^2.0.0
